### ISSUE TITLE
How should I run this project?

### ISSUE THREAD

**Issue by shaghayegh70** [Anemone95/wala-demo#1]
Hi.
I'm trying to use your project to slice but I don't know how can add your project in eclipse and run it and select some code to slice?
I'm not a java developer . Could you help me?

**Comment by Anemone95** [comment]
Sorry for late reply.This project is built by maven. At first, I suggest you use IDEA instead of eclipse. Then, you can read this <https://github.com/Anemone95/wala-demo/blob/master/wala-code/src/main/java/top/anemone/walaDemo/SimpleSlice.java>, which is a demo to show you how to use wala to slice.
